on:
    push:
      branches: [main]
    pull_request:

name: CI

jobs:
  check:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: sudo apt install -y libparted-dev libclang-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build

  fmt:
    name: rustfmt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - run: sudo apt install -y libparted-dev libclang-dev
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
